# Project Report - Data Science 
## Bachelor in Computer Science / PUCPR

Professor Jean Paul Barddal

`Murilo Henrique Ghignatti` - `muriloghignatti@gmail.com`

`Place your name here` - `and your email here`

`Place your name here` - `and your email here`

`Place your name here` - `and your email here`

`Place your name here` - `and your email here`

`2021`

# Import the libs you need

In [1]:
# Import all packages you need here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# etc

# Loading your data

Below, load the data using pandas and make all the necessary data cleansing so that all data types are correct for posterior analysis.

In [ ]:
# Load the df_test
# Média de load = 88.6s | 215.9s
df_test = pd.read_csv("https://www.ppgia.pucpr.br/~jean.barddal/datascience/test.csv")

In [2]:
# Load the df_train
# Média de load = 217.3s | 486.9s | 425.4
#df_train = pd.read_csv("https://www.ppgia.pucpr.br/~jean.barddal/datascience/train.csv")
df_train = pd.read_csv("train.csv")

## Removing Unecessary Data

### Removing the Illegal Data

In [4]:
dropInLine = lambda x: df_train.drop(x, axis=1, inplace=True)

dropInLine("ORIENTACAO_SEXUAL")
dropInLine("RELIGIAO")
dropInLine("PERCENTMASCCEP")
dropInLine("PERCENTFEMCEP")

In [5]:
df_train.head(10)

,HS_CPF,TEMPOCPF,DISTCENTROCIDADE,DISTZONARISCO,QTDENDERECO,QTDEMAIL,QTDCELULAR,CELULARPROCON,QTDFONEFIXO,TELFIXOPROCON,...,QTDDECLARACAOISENTA,QTDDECLARACAO10,QTDDECLARACAOREST10,QTDDECLARACAOPAGAR10,RESTITUICAOAGENCIAALTARENDA,BOLSAFAMILIA,ANOSULTIMARESTITUICAO,ANOSULTIMADECLARACAO,ANOSULTIMADECLARACAOPAGAR,TARGET
0,461547,20.338005,-0.120225,133904.742788,0.540942,-0.593299,-0.458000,0,1.001001,0,...,1.669740,0.734747,-0.146554,-0.380941,0,0,-9999.000000,12.074928,-9999.0,0.0
1,366341,26.790774,2209.766591,171359.052530,0.666880,0.899194,3.154982,0,1.400978,0,...,0.536698,-0.337795,0.844640,0.099724,0,0,-9999.000000,-9999.000000,-9999.0,0.0
2,46288,9.596740,-0.097027,153736.937733,1.292033,-0.542234,2.891115,0,0.785616,0,...,0.944677,-0.253731,0.280378,-0.099915,0,0,-9999.000000,-9999.000000,-9999.0,0.0
3,477900,26.277938,3161.810493,225.077712,1.382572,1.043246,0.721130,0,0.669340,0,...,0.005744,4.205827,2.575026,0.006545,0,0,6.878371,4.477922,-9999.0,0.0
4,136288,4.565429,-9999.000000,-9999.000000,-0.241289,-1.344149,0.310072,0,0.616027,0,...,0.056567,-0.251155,-0.222615,-0.902209,0,0,-9999.000000,-9999.000000,-9999.0,1.0
5,21354,27.322501,0.281108,14215.162684,0.648562,-0.247497,1.190150,0,1.213037,0,...,3.537790,0.292286,0.404854,0.025388,0,1,-9999.000000,-9999.000000,-9999.0,0.0
6,230955,21.211077,-9999.000000,-9999.000000,0.799271,0.583607,1.243659,0,1.027891,0,...,1.849937,10.547869,10.288261,-0.302535,0,0,1.858667,0.807537,-9999.0,0.0
7,117612,3.581023,-9999.000000,-9999.000000,0.439367,-0.070427,-0.398941,0,-0.252604,0,...,-0.398609,-0.220939,-0.614087,0.386378,0,0,-9999.000000,-9999.000000,-9999.0,0.0
8,281786,14.204508,4870.609026,1293.388229,0.459806,-0.829603,-0.116331,0,1.475429,0,...,0.890580,0.557230,-0.696994,-0.134339,0,0,-9999.000000,-9999.000000,-9999.0,0.0
9,470593,23.046139,-0.144046,177606.818218,3.214221,-0.009285,-0.258082,0,2.078237,0,...,0.799435,10.042863,-0.689335,-0.300569,0,0,16.335693,1.140668,-9999.0,0.0

### Rounding Numbers and Replacing null values with nan

In [6]:
def fixIndex(x):
    if not np.isnan(x):
        x = round(x)
        if(x < 0):
            return 0
        else:
            return x

def fixQuantities(df:pd.DataFrame):
    for col in df.columns.values:
        if col.startswith("QTD"):
            df[col] = df[col].apply(lambda x: abs(round(x)) if x != -9999 and not np.isnan(x) else x)
        if col.startswith("DIST"):
            df[col] = df[col].apply(lambda x: abs(x))
        if col == "INDICEEMPREGO":
            df[col] = df[col].apply(fixIndex)

fixQuantities(df_train)
df_train.replace(-9999.000000, np.nan, inplace=True)

In [7]:
# use as many code and text cells you wish
#df_train.describe()
df_train.head(10)

,HS_CPF,TEMPOCPF,DISTCENTROCIDADE,DISTZONARISCO,QTDENDERECO,QTDEMAIL,QTDCELULAR,CELULARPROCON,QTDFONEFIXO,TELFIXOPROCON,...,QTDDECLARACAOISENTA,QTDDECLARACAO10,QTDDECLARACAOREST10,QTDDECLARACAOPAGAR10,RESTITUICAOAGENCIAALTARENDA,BOLSAFAMILIA,ANOSULTIMARESTITUICAO,ANOSULTIMADECLARACAO,ANOSULTIMADECLARACAOPAGAR,TARGET
0,461547,20.338005,0.120225,133904.742788,1.0,1.0,0.0,0.0,1.0,0.0,...,2.0,1.0,0.0,0.0,0.0,0.0,NaN,12.074928,NaN,0.0
1,366341,26.790774,2209.766591,171359.052530,1.0,1.0,3.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0
2,46288,9.596740,0.097027,153736.937733,1.0,1.0,3.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0
3,477900,26.277938,3161.810493,225.077712,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,3.0,0.0,0.0,0.0,6.878371,4.477922,NaN,0.0
4,136288,4.565429,9999.000000,9999.000000,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,1.0
5,21354,27.322501,0.281108,14215.162684,1.0,0.0,1.0,0.0,1.0,0.0,...,4.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.0
6,230955,21.211077,9999.000000,9999.000000,1.0,1.0,1.0,0.0,1.0,0.0,...,2.0,11.0,10.0,0.0,0.0,0.0,1.858667,0.807537,NaN,0.0
7,117612,3.581023,9999.000000,9999.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0
8,281786,14.204508,4870.609026,1293.388229,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0
9,470593,23.046139,0.144046,177606.818218,3.0,0.0,0.0,0.0,2.0,0.0,...,1.0,10.0,1.0,0.0,0.0,0.0,16.335693,1.140668,NaN,0.0

In [31]:
df_train['INDICEEMPREGO'].unique()

array([ 0.,  4.,  6.,  1.,  5., nan,  3.,  2.,  7.,  8.])

# Variable types
* Categorical
  1. Ordinal: This can be a ranking (higher to lower, better to worst)
  2. Nominal: This can be a gender
  3. Binary:  Values that are either x or y such as Yes/No, True/False, 1/0, etc...
* Numerical
  1. Discreet:  Has to be an integer (mathematical meaning)
  2. Continuous: Any value, like height and wight

I will create a table to facilitate the data analysis, each column will be classified with the variable types talked above

In [32]:
#variables = [["Nominal", "Binary", "Continuous", "Continuous", "Nominal", "Nominal",
# "Continuous", "Discreet", "Discreet", "Discreet", "Binary", "Discreet", "Binary",
# "Binary", "Continuous", "Discreet", "Discreet", "Discreet", "Discreet", "Binary",
# "Binary", "Continuous", "Continuous", "Continuous", "Continuous", "Continuous",
# "Binary", "Binary", "Continuous", "Continuous", "Continuous", "Continuous",
# "Continuous", "Discreet"
# ]]

#variables['SEGMENTACAO']

#variables[0].__len__()

# Univariate data analysis

In this section, you should perform univariate data analysis on at least 20 variables. 

In the end, you should describe the main variables that are of your interest, and these should be accounted for in the next sections of the report.
The definition of each variable chosen should be clarified, so arbitrary selections are **not** accepted at this point.

For each variable plotted, make sure you determine the following:
1. The distribution of the data (gaussian, binomial, exponential, etc)
2. Skew
3. Kurtosis
4. Mean, standard deviation, and what they stand for in the context of the dataset

Regardless of the type of the variable being analyzed, make sure you plot it correctly. For instance, make sure scatterplots are not used for categorical data and so forth.

In [ ]:
# place as many cells to plot the visualizations, 
# as well as to describe the main findings

In [ ]:
# if you realize you need to further clean your data here, there is no problem, 
# yet, make sure you are describing the entire process and the rationale 
# behind your choices here

# Multivariate data analysis

In this section, you should plot at least 8 multivariate visualizations. The key here is to investigate underlying correlations and behaviors in the dataset.
Naturally, as visualizations are being created, we should end up with obvious results, yet, you should find at least **TWO** non-obvious behavior in data.

Please follow these steps for creating your visualizations:
1. State an hypothesis. The key here is to explain why you are choosing those specific variables together and what you are expecting to find.
2. Determine what kind of visualization is the most suited.
3. Report the findings and whether they corroborate or not the aforestated hypothesis.


### Hints

In this section, make sure you go beyond naive explorations. For instance, try PCA, t-SNE, and even other techniques we have not worked with during the lectures. The key here is to start to develop a critical mindset towards data analysis and our own work.

### Important

It is strictly forbidden to create multivariate visualizations using variables that were not used in the previous section (univariate analysis).

In [ ]:
# again, feel free to place as many cells to plot the visualizations, 
# as well as describe to the main findings

# Final Plots

In this section, you need to enhance 3 multivariate visualizations that were presented in the previous section of the report.
The key here is to enhance these visualizations with the goal of presenting them for an audience that is not familiar with the dataset used or with data analysis.
**Therefore, make sure that its size, colors, textures, etc, are appropriate are convey the right information to the audience.**

For your final plots, make sure you follow these steps:
1. Present the plot
2. Provide a description of the visualization, including the main findings that we can extract from it


**Hint: take a look at the checklist also made available based on the work of Evergreen.**

In [ ]:
# your code goes here

# Digest

In this section you should write down all the main findings of this exploratory data analysis. Furthermore, you should provide a reflection about your own work and effort during the module, highlighting what you believe you have done well and what you should have done differently. This digest should have at least 2500 characters (no spaces).

```
Add your text here.
```

# Machine Learning

In this section, you should test different machine learning approaches to **build** and **evaluate** your model.

**IMPORTANT: DO NOT FORGET TO REPORT YOUR PREDICTIONS FOR THE TEST DATA. YOU SHOULD BUILD AND EXPORT A FILE ACCORDING TO THE PROJECT DESCRIPTION WITH THE DEFAULTING PROBABILITIES!**

In [ ]:
# use as many cells as you wish.

In [ ]:
# but the sure that all cells are commented adequately!

# Future work

In this cell, please provide at least 3 different ideas that you would like to pursuit within this dataset. That may include, for example, the use of machine learning techniques towards a goal, or analyzing variables that you had no time to during this work. 
Please provide **details** on how you would tackle this problem and provide specifics on which techniques should be used for such purposes.
This section should contain, at least, 2500 characters (no spaces).

```
Add your text here.
```

# Final Steps

1. Save this report as a jupyter notebook (`.ipynb`)
2. Save a copy of this report as a PDF file (`.pdf`)
3. Copy the dataset
4. Zip it all together within a single file (`<your_name>.zip`)
5. Send it over using Blackboard.